### ISSUE TITLE
Broken Podcast Feed on WP Engine

### ISSUE THREAD

**Issue by nikola3244** [WP-for-Church/Sermon-Manager#12]
https://wordpress.org/support/topic/broken-podcast-feed-on-wp-engine/

**Comment by nikola3244** [comment]
This might have been fixed in c780866444bd5dc1c971b4def2fa1b1d62cef977

**Comment by igor-gp** [comment]
Got this response from the user:

**After the last update, the feed validates but with errors...**

http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fvictorybaptistpocono.com%2Ffeed%2Fpodcast

**Comment by nikola3244** [comment]
Why do you say that there are errors? That website says that it is valid.

-----Original Message-----

**Comment by nikola3244** [comment]
Checked it again. Feed is valid. Closing this one.
