### ISSUE TITLE
Player audio tag without source

### ISSUE THREAD

**Issue by ordimission** [WP-for-Church/Sermon-Manager#125]
Hello,
Thank you for your work. However,  your player is no more working for me.
When I look at the source of your code, I see : audio controls preload="metadata" class="wpfc-sermon-player"
But there is no source src="file.mp3" inside. Am I missing something ?
![sermonmanager_player_issue](https://user-images.githubusercontent.com/6873588/31252780-9e63b312-aa22-11e7-97b5-61bddc98ccca.png)

Regards,
Fabrice

**Comment by ordimission** [comment]
Just some information : version 2.8.2 of the plugin SermonManager, WP 4.8.2 with Genesis Gallery Pro theme 2.5.2. Browser : firefox 55.0.2
Fabrice

**Comment by nikola3244** [comment]
Thank you for reporting the issue and sending so many details! :+1: 
If every user was like you eh :smile: 

Fixed in 08c4842ffdcc57792e9d9f4efa344fe224b2b22a

**Comment by ordimission** [comment]
Thank you so much for your quick fix. I have updated to 2.8.3 release and confirm you it is now working.
