### ISSUE TITLE
Podcast feed with relative url

### ISSUE THREAD

**Issue by ScarlettCode** [WP-for-Church/Sermon-Manager#137]
When using the podcast section if you used relative url's when uploading sermons it doesn't create the feed correctly.

https://christchurchpmb.co.za/sermons/feed

If you look at the enclosure url 

		        <enclosure url="https://christchurchpmb.co.za/sermonarchive/2017/October/15October2017PMSermon.mp3" length="0" type="audio/mpeg"/>

vs

		        <enclosure url="/sermonarchive/2017/October/15October2017AMSermon.mp3" length="0" type="audio/mpeg"/>

If I want to update all my previously uploaded sermons where in the wordpress database would I find the urls?

Regards
Michael

**Comment by nikola3244** [comment]
Hey Michael,

Thanks for the report, it will be fixed tomorrow probably.

>If I want to update all my previously uploaded sermons where in the wordpress database would I find the urls?

`sermon_audio` will be `meta_key` in `{$prefix}postmeta` (most likely `wp_postmeta`)

**Comment by nikola3244** [comment]
It has been fixed. You can download the development version in couple minutes when build completes :)

(download from [here](https://downloads.wordpress.org/plugin/sermon-manager-for-wordpress.zip))

**Comment by ScarlettCode** [comment]
@nikola3244 That download link has the fix but the version in sermons.php is still 2.8.6 instead of 2.9. Think it needs to be bumped?

**Comment by nikola3244** [comment]
Version will be bumped in the _release_ phase of the development. <sup>[[1]](http://nvie.com/posts/a-successful-git-branching-model/#release-branches)</sup>
