### ISSUE TITLE
Podcast feed duration value

### ISSUE THREAD

**Issue by ScarlettCode** [WP-for-Church/Sermon-Manager#140]
When viewing our podcast [feed ](https://christchurchpmb.co.za/sermons/feed) all the durations are 0. The makes sense as I've never set the time for the mp3 before. 

Looking in the admin view my understanding is that the plugin will auto work it out if left blank (image below)

![image](https://user-images.githubusercontent.com/786389/32037349-3c7e36e6-ba25-11e7-98dd-77a525fdd861.png)

If I go and look at previous sermons that have been saved there is no time in that box. Does that mean it isn't calculating the time? Or just doesn't actually save away the calculated time?

If it is calculating the time can we add it to the podcast feed? Otherwise is there something special about the mp3's I'm using that will allow it to calculate the time?

Thanks
Michael

**Comment by nikola3244** [comment]
Hello Michael,

The code will _attempt_ to automatically calculate the mp3 duration, but it's not perfect.

>Looking in the admin view my understanding is that the plugin will auto work it out if left blank (image below)

Yes, you are correct, but there's something preventing it from calculating.

>If I go and look at previous sermons that have been saved there is no time in that box. Does that mean it isn't calculating the time? Or just doesn't actually save away the calculated time?

It probably just isn't calculating time.

>[...] Otherwise is there something special about the mp3's I'm using that will allow it to calculate the time?

No promises, but we will download your mp3 files and check if there's some issue - but that will happen when we get some free time.

So, for now, just input the duration manually. :)

Thank you for understanding.

**Comment by nikola3244** [comment]
Hi @ScarlettCode, the issue has been [fixed](5181af01e2f7b9d4824e426849dd9059011b403b) in 2.15.0
