### ISSUE TITLE
Audit use of !important in css

### ISSUE THREAD

**Issue by igor-gp** [WP-for-Church/Sermon-Manager#149]
There are lots of instances where we use !important in css, apparently around 40 times. Please audit this and see if we can reduce this.

**Comment by igor-gp** [comment]
Another user just wrote:

```Currently the css that handles the grid uses !important values to display a two column grid, making it difficult to override in styles.css. ```

**Comment by nikola3244** [comment]
CSS has been rewritten, closing this :slightly_smiling_face:
