### ISSUE TITLE
This feed does not validate, after most recent update.

### ISSUE THREAD

**Issue by timothymolter** [WP-for-Church/Sermon-Manager#154]
This feed does not validate.

line 8, column 59: XML parsing error: <unknown>:8:59: duplicate attribute [help]

	xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">

Link: http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Ffeeds.feedburner.com%2FCCFFStudies%3Fformat%3Dxml

**Comment by nikola3244** [comment]
Hello, the bug has been fixed in [2.10.1](https://github.com/WP-for-Church/Sermon-Manager/tree/master#2101). 

Please update to latest version (2.10.2). But if you are already using latest, then please comment and we will investigate further.

**Comment by timothymolter** [comment]
That did the fix. Thank you so very much!
