### ISSUE TITLE
API ignores several parameters

### ISSUE THREAD

**Issue by yusufk** [WP-for-Church/Sermon-Manager#160]
I'm using the API with CURL like this:
`curl -X POST \
  http://www.mysite.org/site/wp-json/wp/v2/wpfc_sermon \
  -H 'Authorization: Basic basicdsfsdfsdfs==' \
  -H 'Content-Type: application/json' \
  -d '{"title":"test post",
"status":"publish",
"wpfc_sermon_series":95,
"wpfc_service_type":113,
"sermon_description": "test sermon",
"sermon_audio":"https://ia600603.us.archive.org/4/items/Itest.mp3"
}'`

A sermon does get added, however, it is missing the sermon_audio and sermon_description. Any ideas?

**Comment by nikola3244** [comment]
Hey, resolved now. Please download the latest package from `dev` branch.

Thank you for reporting the issue!

**Comment by yusufk** [comment]
Awesome, thank you, will do.

**Comment by nikola3244** [comment]
You can also just install 2.11.1, fix is released officially :smile:

**Comment by wosephj** [comment]
Hi, I noticed an issue with a few other fields.

Sermon video links aren't working. It looks like `SM_API.save_custom_data() `has a typo. `sermon_video_url` should be `sermon_video_link`.

Also, I could not find a way to set sermon duration/length. `sermon_audio_duration` was not working for me. It wasn't as immediately clear to me what the problem might be here.
