### ISSUE TITLE
Order sermons by sermon date + published time

### ISSUE THREAD

**Issue by nikola3244** [WP-for-Church/Sermon-Manager#161]
If multiple sermons are set to same serrmon_date, they will be ordered by alphabetical order on that day.

I.e. there are three sermons set to 12/12/2012, named "Sermon", "Test", "Name". 
We want them in that order, but they will be ordered as:

- "Name"
- "Sermon"
- "Test"

Because "N" comes before "S" and "T".

**Proposed solutions:** 
- During sermon saving, add published _time_ to serrmon_date meta (unix_time(sermon date) + unix_time(time))
- Modify ordering arguments to "meta_field published" (not checked the actual values), so it 
orders by published date if serrmon_date is same

**Comment by robertmain** [comment]
Just chipping in here to say that this isn't (completely) fixed. I had two sermons, one called _"What's with you?"_ and one called _"Zealous People in the Emperor’s World"_. They were ordered correctly until I saved changes to the latter, which caused them to be incorrectly ordered.

**Comment by nikola3244** [comment]
Ah, thanks for the report. 

Could you please open a new issue with the details on how to reproduce + environment details (WP/PHP/SM version + timezone setting), and I'll take a look ASAP.

**Comment by robertmain** [comment]
Sure, will do.

**Comment by robertmain** [comment]
@nikola3244 Regarding including WP/PHP/SM version, you've reminded me of something...HMB...

**Comment by robertmain** [comment]
Okay, check out #189
