### ISSUE TITLE
Wrong sorting of Sermons at the same day

### ISSUE THREAD

**Issue by hermiePRO** [WP-for-Church/Sermon-Manager#162]
Hi there,
i noticed a wrong sorting of the sermons.
We hat a few sermons at the same day.

Although i set different dates (different hours), it doesnt sort it as it should be.

[https://stage.fcg-bielefeld.de/prediger/ingolf-ellssel/](url)

**Comment by nikola3244** [comment]
Hey, thanks for the issue report, but we already have an existing issue open for it (#161)

**Comment by nikola3244** [comment]
Just FYI, this has been fixed just now
