### ISSUE TITLE
Add preacher term & alternative attachment download in archive & single pages

### ISSUE THREAD

**Issue by hermiePRO** [WP-for-Church/Sermon-Manager#166]
Hi there, 
since i programmed a custom displaying of the attachment downloads in single & archive pages for my .mp3 Files (in template-tags.php)  i always have to customize the code after plugin update.

Maybe there is a way to include this to plugin or to outsource the code for single&archive-pages?
In my opinion, the displaying of attachments in this way looks much more tidy

---
Could you add an option to display the term "Preacher" before the name? 

![image](https://user-images.githubusercontent.com/22779096/35503152-96d0d8e2-04df-11e8-9623-a5a19ec0d664.png)

`/*  KH CUSTOM  MP3 Download*/
				if ( get_wpfc_sermon_meta( 'sermon_audio' ) ) {
					echo 'Download: <a href="' . get_wpfc_sermon_meta( 'sermon_audio' ) . '" class="sermon-attachments" download><span class="dashicons dashicons-media-audio"></span>' . __( 'MP3', 'sermon-manager-for-wordpress' ) . '</a>';
				}`

**Comment by nikola3244** [comment]
Hey there, 

We've just added a filter for you to use, [couple minutes ago](https://github.com/WP-for-Church/Sermon-Manager/commit/5b58fe85c9d65bd50ad2a669779c08dad94d58b4). No modification will be lost on plugin update that way. You can use it on your website if you download and install the [development release](https://downloads.wordpress.org/plugin/sermon-manager-for-wordpress.zip). (Note: You might need to remove existing Sermon Manager, but no data will be lost in the process.)

I've modified your code to work with the filter. Just place it at the end of your (child) theme's `functions.php`, or you can [create a separate plugin for it](https://codex.wordpress.org/Writing_a_Plugin#Creating_a_Plugin).

```
/* KH CUSTOM MP3 Download*/
add_filter( 'sm_attachments_html', function () {
	if ( get_wpfc_sermon_meta( 'sermon_audio' ) ) {
		return 'Download: <a href="' . get_wpfc_sermon_meta( 'sermon_audio' ) . '" class="sermon-attachments" download><span class="dashicons dashicons-media-audio"></span>' . __( 'MP3', 'sermon-manager-for-wordpress' ) . '</a>';
	}

	return '';
} );
```

Note, this code will disable displaying of notes, bulletin, etc. If you want to just change audio output, use the following code (I've just modified it further, to include the rest of the code from `wpfc_sermon_attachments()` function. You can modify the whole output in here.):

```
/* KH CUSTOM MP3 Download*/
add_filter( 'sm_attachments_html', function () {
	$html = '<div id="wpfc-attachments" class="cf">';
	$html .= '<p><strong>' . __( 'Download Files', 'sermon-manager-for-wordpress' ) . '</strong>';
	if ( get_wpfc_sermon_meta( 'sermon_audio' ) ) {
		$html .= 'Download: <a href="' . get_wpfc_sermon_meta( 'sermon_audio' ) . '" class="sermon-attachments" download><span class="dashicons dashicons-media-audio"></span>' . __( 'MP3', 'sermon-manager-for-wordpress' ) . '</a>';
	}
	if ( get_wpfc_sermon_meta( 'sermon_notes' ) ) {
		$html .= '<a href="' . get_wpfc_sermon_meta( 'sermon_notes' ) . '" class="sermon-attachments" download="' . basename( get_wpfc_sermon_meta( 'sermon_notes' ) ) . '"><span class="dashicons dashicons-media-document"></span>' . __( 'Notes', 'sermon-manager-for-wordpress' ) . '</a>';
	}
	if ( get_wpfc_sermon_meta( 'sermon_bulletin' ) ) {
		$html .= '<a href="' . get_wpfc_sermon_meta( 'sermon_bulletin' ) . '" class="sermon-attachments" download="' . basename( get_wpfc_sermon_meta( 'sermon_bulletin' ) ) . '"><span class="dashicons dashicons-media-document"></span>' . __( 'Bulletin', 'sermon-manager-for-wordpress' ) . '</a>';
	}
	$html .= '</p>';
	$html .= '</div>';

	return $html;
} );
```
