### ISSUE TITLE
Sidebar Request

### ISSUE THREAD

**Issue by green15p** [WP-for-Church/Sermon-Manager#173]
In order to keep our site uniform, I would like to request a way to have the sidebar visible on the single sermon page. Right now, I click on the sermon from the archived page and it brings up a full page template. I would like the option to add the sidebar on this page. Thank you and let me know if you need more clarification.

**Comment by nikola3244** [comment]
Hi,

What theme are you using?

Also, the sidebar should show on single and archive pages.

Note: You might try to check option named "Theme Compatibility" in Sermon Manager Settings, it might resolve the issue.

**Comment by green15p** [comment]
Theme compatibility worked. Thank you.

**Comment by green15p** [comment]
I'm still new to the plugin

**Comment by green15p** [comment]
On the single page, the volume is sitting on top of the download link for the MP3. I am using theme twenty thirteen.
