### ISSUE TITLE
Single Sermon Page: Audio player issue

### ISSUE THREAD

**Issue by green15p** [WP-for-Church/Sermon-Manager#174]
On the single sermon page, the volume is sitting on top of the download link for the MP3. I am using theme twenty thirteen.

**Comment by nikola3244** [comment]
Hi, can you please send us the URL of the page where the issue occurs?

**Comment by green15p** [comment]
http://newhopeofchester.com/sermons/stages-spheres-in-discipleship 

I'm use in google Firefox.

**Comment by green15p** [comment]
Also under the series, there is a problem. It shows the featured image twice. 

http://www.newhopeofchester.com/sermons/series/biblical-discipleship

**Comment by nikola3244** [comment]
Hi,

We will investigate the issue with audio player, thank you for reporting it.

Regarding the double image, please to the following:

1. Log into your website's admin area
2. On the left side, hover on "Appearance" menu item
3. In the submenu that has opened, click on "Custom CSS", or "Edit CSS", or "Customize"
4. Copy & paste the following CSS snippet into the ediotor
```
article.wpfc_sermon .wpfc-sermon-image {
  display: none;
}
```
5. Save the page

**Comment by adi8i** [comment]
Hello @green15p ,

Can you enable `plyr` please, so I can debug the issue?
I am not able to reproduce the bug on our end and I noticed your website use custom views.

**Comment by green15p** [comment]
I enabled it and it can be found here. http://newhopeofchester.com/sermons/stages-spheres-in-discipleship only in firefox. it works fine in chrome.

**Comment by adi8i** [comment]
It shows fine on my end on both Firefox and Chrome, here's a screenshot.
![screenshot-2018-3-21 part 2 stages spheres in discipleship new hope christian fellowship](https://user-images.githubusercontent.com/9744973/37710738-3784f21e-2d17-11e8-83e7-6654eade3e6c.png)
