### ISSUE TITLE
The [sermons] shortcode always loads the full sized image

### ISSUE THREAD

**Issue by renehamburger** [WP-for-Church/Sermon-Manager#181]
Whether the image_size property is present or not, it is always the full image that is loaded and displayed. It seems that this issue can already be observed on [your demo site](https://demo.wpforchurch.com/sermon-manager/sermons/). 
A related issue occurred before and was fixed in 2.8, but I'm using 2.12.5.

**Comment by nikola3244** [comment]
Thanks for the report! It has been fixed.
