### ISSUE TITLE
Sermon/Post Excerpts

### ISSUE THREAD

**Issue by robertmain** [WP-for-Church/Sermon-Manager#183]
It appears that Sermon Manager doesn't currently support excerpts. This is a shame because sometimes the priest at my church likes to post a small snippet of (for want of a better term) "teaser text" for each sermon.

I'd like to put a PR together to address this but wanted to test the water first...

**Comment by robertmain** [comment]
Sure. Out of interest why does Sermon Manager use those custom fields instead of `post_content` and `post_excerpt`? I wrote some SQL to import WordPress blog posts into Sermon Manager(happy to share this for a knowledge base article or something if you like) and came across them along the way.

**Comment by nikola3244** [comment]
To be honest, I don't know. That was the original functionality from the previous (and original) developer, before we took over the plugin. They only know why they decided to use it, we just rolled along it.

Also, FYI, it's not smart to put any custom data into sermon's `post_content` and `post_excerpt`, since they get overwritten on sermon update. For compability reasons, we render there a "plain" view, such as:
```
Bible Text:  0:0-0 | Speaker: Test Preacher

Message Description
```
That is used on search pages, for example, when we can't override the displayed content.

----
I think that I've got an email with some SQL queries, most likely from you - and thank you. Sharing knowledgde is always very welcome.
We might even implement that feature, to create a WordPress posts importer. (we already have three importers: from defunct Sermon Browser, Series Engine, and from Sermon Manager's export file)

**Comment by robertmain** [comment]
Well I was thinking that you could keep the sermon description or whatever in `post_content`, then you could support `post_excerpt` then just keep the bible text, speaker etc. in the metadata table.

As for displaying that information, surely you could just re-create that kind of display internally with a hook or something. That way it would also keep the metadata (like the bible text) out of the post content field (where it really doesn't belong anyway imho) and it would mean you didn't have to do regex hackery to parse it out :)

It actually wasn't from me - but I did post it on the wordpress forums. [This is it](https://gist.github.com/robertmain/d32062477ca35f49e3377a783bc25c05).

**Comment by nikola3244** [comment]
Great suggestion, I wish I had the time to adjust the behavior. :wink: 

Sermon content would be saved in `post_content` *and* `sermon_description` (for backwards compatibility). While excerpt would go where it's supposed to. If you have time and desire to go through code and modify the behavior & update references - go for it, if not - I'll do it when I get time (it will take a while).

For now, just disable content creaton for `post_excerpt`. ([here](https://github.com/WP-for-Church/Sermon-Manager/blob/dev/sermons.php#L376)) And make the new field save into it.

Also, if you ever have a different idea, let me know, I might suggest bad ideas. :stuck_out_tongue_winking_eye:

**Comment by robertmain** [comment]
Maybe in the interests of resolving this particular issue and not introducing a (potentially) breaking change at present, I could make it just use a custom field and then put another PR in later to refactor and remove the custom fields?

**Comment by nikola3244** [comment]
Sure, as long the exsiting functionality is refactored before the release. :slightly_smiling_face: 

If we make a release with the custom field, we will have to support it in future, for backwards compability.

**Comment by robertmain** [comment]
Well, my plan would be to go ahead with this as a custom field like everything else. Then later on put another PR in that removes the custom fields and just saves everything to `post_content` and/or `post_excerpt` etc. There are some fields we'd need to keep like `sermon_date` since `post_date` is not necessarily the date the sermon was actually preached. However we could probably find ways to make it play nicely and not break people's sites that use the custom field

**Comment by nikola3244** [comment]
Sure, go with custom field! We'll refactor that later.

Sermon date is a touchy topic, we had some major issues (read: drama) with it in the past, but it's been very quiet since I've put some serious time for it and rewrote it completely. :slightly_smiling_face:
