### ISSUE TITLE
Revisions missing in admin

### ISSUE THREAD

**Issue by robertmain** [WP-for-Church/Sermon-Manager#186]
Sermon manager doesn't appear to support the standard revisions that normal wordpress blog posts do(see below)

![image](https://user-images.githubusercontent.com/537684/38786153-2005a2b4-40f4-11e8-8d71-6d135a258fbc.png)

**WordPress Version:**  4.9.5
**Sermon Manager Version:** 2.12.5

**Comment by nikola3244** [comment]
Actually, that was intentionally removed, IIRC. Someone could take a look and get it back. :+1:

**Comment by robertmain** [comment]
>that was intentionally removed

Why?

**Comment by nikola3244** [comment]
I think it was breaking something in Sermon Manager when we took over, but I honestly can't remember, it was too long ago. Maybe there's a note somewhere in code.

Sermon Manager was refactored extensively through the time, so I doubt that it is still an issue anymore. 

Anyway, it could be added back, not a big deal

**Comment by robertmain** [comment]
Ah, interesting. I figured there'd be a good reason. Also, as I'm going through the codebase I'm noticing a lot of `deprecated-functions.php` and `myfunctionname_v2` etc. Is there an effort in place to refactor these out that I can join in with?

**Comment by robertmain** [comment]
>PHPUnit, you got here at the right time. 😉

You could say, I was a....[godsend](https://www.youtube.com/watch?v=6YMPAH67f4o)

Okay, but joking aside - I'd be happy to help out with that. You're welcome to check out the projects I've been working on recently to see the kind of testing stuff I do:

- https://github.com/robertmain/codeigniter-starter/tree/master/tests
	- https://github.com/robertmain/codeigniter-starter/blob/model-validation/tests/models/UserTest.spec.php
	- https://github.com/robertmain/codeigniter-starter/blob/model-validation/tests/models/Model.spec.php
- https://github.com/joshmarinacci/node-pureimage
	- https://github.com/joshmarinacci/node-pureimage/blob/master/tests/unit/specs/pureimage.test.js

>Code definitely could be better, but it's much better than how it was even just a month ago. Not to mention 6 months, or a year! It was one very big mess.

Yeah, I wasn't meaning to be rude :). Just wondered if you wanted a hand refactoring :D

**Comment by nikola3244** [comment]
Thanks for the projects, I'll definitely check them tomorrow. But you are
more than welcome to help anytime. :)
I'm pretty new to PHPUnit testing in WordPress (have been experimenting
with pure PHP unit testing), so I'm still learning.

And no, no, I didn't even consider that you were rude, I just made a note,
hehe. Hard to judge the tone via text. :)
I maybe should've put ":D" at the end of that paragraph, it would've
sounded completely different.

PS: If you ever want to help but don't know what to do, you can take a look
at issues and pick one - I'll help alongside and provide
information/feedback. (FYI: Issues labelled with `Good First Issue` are
easier and simpler to resolve)
