### ISSUE TITLE
Sermons preached on the same date are incorrectly sorted

### ISSUE THREAD

**Issue by robertmain** [WP-for-Church/Sermon-Manager#188]
**WP Version:**  5.0-alpha
**SM Version:** 2.12.5
**PHP Version:** 7.1.9

Time Zone is set to New York, which is currently GMT -4(daylight savings)

Recurrence of #161

**Comment by nikola3244** [comment]
Hi Robert, 

I've finally took a look and I can not reproduce it. The sermons are ordered properly. There was maybe some related change that fixed the issue in the meantime. Could you please try it out now, with the changes from `dev` branch?

Thanks!

## Test scenario

Title: **Sermon 1**
Date Preached: **29/05/2018**
Date Published: **May 29, 2018 @ 18:00** 

Title: **Sermon 2**
Date Preached: **29/05/2018**
Date Published: **May 29, 2018 @ 21:00** 

Outcome: **Sermon 2** shows up before **Sermon 1**.

**Comment by robertmain** [comment]
Hmmm, I'm having trouble reproducing this too. Closing for now. It may have been fixed in the meantime.
