### ISSUE TITLE
"Subscribe" links (Like in Sermon Browser)

### ISSUE THREAD

**Issue by PainFreeComputing** [WP-for-Church/Sermon-Manager#193]
I would like to see this implemented in Sermon Manager exactly as it worked in Sermon Browser (now unsupported / defunct).

On the Sermons page, or any filtered list, include a link to subscribe to a podcast of the selected list -- both via itpc and http.

![generic_subscribe](https://user-images.githubusercontent.com/35268211/39162622-0cc67c20-473c-11e8-86de-063567e45b21.png)
![itunes_subscribe](https://user-images.githubusercontent.com/35268211/39162625-0f849258-473c-11e8-8d07-ad0601a34be4.png)
[sermons.xml.txt](https://github.com/WP-for-Church/Sermon-Manager/files/1940613/sermons.xml.txt)

**Comment by scottdwest** [comment]
The ability to use buttons (like on https://www.theincomparable.com/theincomparable/) not just text might be nice.

Users could submit different services and the URL formulas to make them work, along with custom buttons.
