### ISSUE TITLE
Multiple feeds

### ISSUE THREAD

**Issue by nikola3244** [WP-for-Church/Sermon-Manager#198]
A customer requested an interesting feature that we could implement.

We could have different feeds for specific service types.

My quick idea is to check if `service_type` GET exists, and then just to modify the WP_Query arguments.

Example URL: `https://example.com/?feed=rss2&post_type=wpfc_sermon&service_type=morning-service`

**Comment by scottdwest** [comment]
Whats the difference between the url in your example and the feed as generated by WordPress?:  https://example.com/service-type/morning-service/feed/

**Comment by nikola3244** [comment]
You are a lifesaver :wink: 

I honestly didn't know that we had that feature, but WordPress is smart. 

The only difference between your and my URL is that yours uses URL rewriting, and mine has an error.
This one would work the same as yours: `https://example.com/?feed=rss2&post_type=wpfc_sermon&wpfc_service_type=morning-service`

Thanks for this!

**Comment by scottdwest** [comment]
We are also just starting to need multiple feeds for different service types and whilst my solution does validate it doesn't generate any results. when I use the URL you suggested I get results but the feed dose not validate specifically the Atom:link tag url is invalid, apparently it needs to be escaped. the Feed is correctly doing this on the title tag.

The feed is accepted by Feedly, but not by Feedburner.

**Comment by nikola3244** [comment]
@scottdwest Hey there, if there's a new bug, it would be nice to open a new issue about it :slightly_smiling_face:

**Comment by scottdwest** [comment]
@nikola3244 I have opened a new issue. I mention it here also, as it makes my previous advice in this thread incorrect.
