### ISSUE TITLE
Sermons published via API don't have preached date auto-generated

### ISSUE THREAD

**Issue by yusufk** [WP-for-Church/Sermon-Manager#205]
### Expected Behaviour

1. When posting using the API, the sermon should be viewable on the blog.

### Actual Behaviour

1. The sermon needs to be manually edited and then published again before its visible

### Steps To Reproduce

1. 

`
curl -X POST \
  https://www.site.org.za/site/wp-json/wp/v2/wpfc_sermon \
  -H 'Authorization: Basic bdfsfdfsdfsdfsdfdsvccwevbeb==' \
  -H 'Content-Type: application/json' \
  -d '{"title":"'"$TITLE"'","status":"publish","wpfc_sermon_series":95,"wpfc_service_type":113,"wpfc_preacher":13,"sermon_audio":"'"$URL"'"}'
`

### Platform
**Sermon Manager Version: 2.12.5**
**WordPress Version: 4.9.6**
**PHP Version:**

**Comment by nikola3244** [comment]
That's weird, your example request works just fine over here - sermon is published. 
Tried both in 2.12.5 and in latest `dev` branch

Could you please try again (please make sure that there's `"status":"publish"`)?
If there's still an issue, we'll get onto debugging it :slightly_smiling_face:

**Comment by nikola3244** [comment]
That's true. Date Preached is recommended to be set. One thing that could
aid this is that I could add a function that would put Date Published as
Date Preached when it's not set - how does this sound? :)

**Comment by yusufk** [comment]
Sounds perfect!

**Comment by robertmain** [comment]
I'd say that this is a bug in itself. I came across this when I wrote my SQL import script.

@yusufk just guessing but have you tried passing `sermon_date` across to the API as a unix timestamp?

@nikola3244 I'd suggest that maybe sermon manager should assume date published if date preached isn't provided (especially because date preached is apparently optional according to the GUI)

**Comment by yusufk** [comment]
Looks, like I hadn't. I just did now though and the field is populated.

**Comment by robertmain** [comment]
I have some SQL somewhere that will go through and update your existing posts if you're interested

**Comment by yusufk** [comment]
That would be great, thank you @robertmain

**Comment by nikola3244** [comment]
@yusufk: to update existing Sermon Dates, just do the following:

1. Open Sermon Manager Settings
2. Go to "Debug" tab
3. In the option named "Execute a specific update function", select "sm_update_28_fill_out_empty_dates"
4. Click on "Save Settings"

It's safe and easy. :slightly_smiling_face: 

@robertmain:
> I'd suggest that maybe sermon manager should assume date published if date preached isn't provided (especially because date preached is apparently optional according to the GUI)

Yup, that's how it's going to work. :slightly_smiling_face: 

Internally, all sermons are sorted by `sermon_date` (date preached) meta, no matter if it's set or not. In the case when a sermon is created (non-API) without date preached, there's a function that would automatically create it from the published date, and mark it as "auto-update" - so it's not shown in the editor (even though it's in the database), and it would update on date published update. Does that make sense?
