### ISSUE TITLE
Enhancement Request - Add support for custom roles

### ISSUE THREAD

**Issue by zSeriesGuy** [WP-for-Church/Sermon-Manager#209]
I would like to see support for custom roles so that access and contribution can be delegated.
This is easily implemented in the register_post_type and register_taxonomy calls.
With this implementation, someone using a role manager such as Members can create custom roles to delegate authority to contribute and manage the sermons.

I have already made the changes in my copy of the code. This is what I did. The changes are in class-sm-post-types.php.
I added the following just before the first register_taxonomy.
`		$capabilities = array(
                     'manage_terms' => 'manage_wpfc_categories',
                     'edit_terms'   => 'manage_wpfc_categories',
                     'delete_terms' => 'manage_wpfc_categories',
                     'assign_terms' => 'manage_wpfc_categories');
`
Then I added this to each register_taxonomy:
`				'capabilities' => $capabilities,
`
In the register_post_type call, I changed capability_type => 'wpfc_sermon' and added:
`            'capabilities'        => array(
                'manage_wpfc_categories'  => 'manage_wpfc_categories',
                'manage_wpfc_sm_settings' => 'manage_wpfc_sm_settings'),
`
Finally, to add these capabilities to the built-in roles for administrator, editor, and author, I added the following right after the register_post_type:
`        
        // Add sermon managing capabilities to administrator, editor, author.
        $role = get_role( 'administrator' );
        if ( is_object( $role ) && ! $role->has_cap( 'edit_wpfc_sermon' ) ) {
            $role_list = array( 'administrator', 'editor', 'author' );
            foreach ( $role_list as $role_name ) {
                $role = get_role( $role_name );
                if ( null === $role || ! ( $role instanceof WP_Role ) ) {
                    continue;
                }
                // Read sermons.
                $role->add_cap( 'read_wpfc_sermon' );
                // Edit sermons.
                $role->add_cap( 'edit_wpfc_sermon' );
                $role->add_cap( 'edit_wpfc_sermons' );
                $role->add_cap( 'edit_private_wpfc_sermons' );
                $role->add_cap( 'edit_published_wpfc_sermons' );
                // Delete sermons.
                $role->add_cap( 'delete_wpfc_sermon' );
                $role->add_cap( 'delete_wpfc_sermons' );
                $role->add_cap( 'delete_published_wpfc_sermons' );
                $role->add_cap( 'delete_private_wpfc_sermons' );
                // Publish sermons.
                $role->add_cap( 'publish_wpfc_sermons' );
                // Read private sermons.
                $role->add_cap( 'read_private_wpfc_sermons' );
                // Manage categories & tags.
                $role->add_cap( 'manage_wpfc_categories' );
                // Add additional roles for administrator
                if ( 'administrator' === $role_name ) {
                    // Change calendar themes & manage calendar options.
                    $role->add_cap( 'manage_wpfc_sm_settings' );
                }
                // Add additional roles for administrator and editor
                if ( 'author' !== $role_name ) {
                    $role->add_cap( 'edit_others_wpfc_sermons' );
                    $role->add_cap( 'delete_others_wpfc_sermons' );
                }
            }
        }
`
I added the manage_wpfc_sm_settings. But I did not make the changes in class-sm-admin-menus.php to assign this capability to add_submenu_page calls. The 'manage_options' capability on the submenus could be changed to 'manage_wpfc_sm_settings' or whatever you might want to call it.

I hope you will consider implementing this so that I won't loose my changes when the code gets updated. It works pretty good and in Members plugin, Sermons shows up as a selectable column.
![image](https://user-images.githubusercontent.com/12520869/41129942-648deb5a-6a82-11e8-8218-6bccb78fb41e.png)

**Comment by nikola3244** [comment]
Hi there!

This is a wonderful contribution, thank you.

Could you please create a pull request, so I can review the code, make some changes if needed, and incorporate it into the next release? (which will happen really soon! - in couple hours or tomorrow)

**Comment by zSeriesGuy** [comment]
Unfortunately, I have never used github to manage/change code. So I don't really know what I'm doing with the pull request. I read thru some of the doc. But just don't quite get it. I created a pull request and it said I wanted to merge 111 changes. So I'm thinking I chose the wrong branch or something.

**Comment by nikola3244** [comment]
Let's go through whole process in few steps:

1. Click on the `Fork` button in the top right of the page, right under your profile photo in the corner
2. A new page will open, and that will be the page of your own "clone" of Sermon Manager's code (by the wat, you can do whatever you want on that clone, and nothing that we do here will impact it)
3. Make sure that it says `Branch: dev` above the list of directories and files
2. Modify the required code (add the code for custom roles)
3. When you have finished editing, committed the changes, etc... go to the [fork home](https://github.com/zSeriesGuy/Sermon-Manager), and click on "New pull request", right above the list of directories and files, just like `Branch: dev`
4. Make sure that `base-fork` is `WP-for-Church/Sermon-Manager` and `base` is `dev`
5. Make sure that `head-fork` is `zSeriesGuy/Sermon-Manager` and `compare` is `dev`
6. After that, add a title, and submit the pull request

Next time when you want to add some changes to the code, just do steps 2-6 again :slightly_smiling_face:

**Comment by zSeriesGuy** [comment]
Done. Hopefully correctly. Excellent instructions. Thanks a bunch.

**Comment by nikola3244** [comment]
Merged. Thank you.
