### ISSUE TITLE
Custom archive page slug no longer works

### ISSUE THREAD

**Issue by robertmain** [WP-for-Church/Sermon-Manager#213]
### Expected Behaviour

Setting "Archive Page Slug" should allow me to change the "sermons" part of the URL to "homily" or something else.

### Actual Behaviour

The archive page slug stays the same no matter what I change it to. Links to individual posts change, however - they just lead to a 404 page.

### Steps To Reproduce

1. Navigate to "Settings" under Sermon Manager
1. Change "Archive Page Slug" to any value
1. Navigate to sermon archive page
1. Click on a sermon

### Platform
**Sermon Manager Version:** 2.13.0
**WordPress Version:** 4.9.5
**PHP Version:** 7.1

**Comment by robertmain** [comment]
This is still broken on 2.13.1

**Comment by nikola3244** [comment]
Hm, weird. I did confirm the bug and the solution on my testing instance, before pushing the patch.

Are you maybe using some caching plugins?

**Comment by robertmain** [comment]
I'm using WP Super Cache, but I cleared the cache. Lemme try it on my staging site and get back to you.

**Comment by robertmain** [comment]
Hmm, well I'm running Sermon Manager on there and I set the archive page slug to `abc`. https://staging.saintjohnschurch.com/abc
![image](https://user-images.githubusercontent.com/537684/41324587-47c81766-6e83-11e8-9911-92207e8b837b.png)


Granted, I'm running WP 5.x on there (dev version). Lemme do a fresh install of WP on my local machine and gather some more info if I can

**Comment by robertmain** [comment]
...wait a goddamn second....it seems to be working now

**Comment by robertmain** [comment]
Got it! I mucked up `wp_cron` so the update task to change all the sermon URLs isn't running. 

Basically I changed `wp_cron` so that it gets run by crontab rather than on page load. Problem is, I screwed something up so it's never getting called...

My mistake. Looks like it's working as intended.
