### ISSUE TITLE
Speaker Ordering

### ISSUE THREAD

**Issue by robertmain** [WP-for-Church/Sermon-Manager#214]
### Expected Behaviour

The speakers should either be ordered according to the `order` attribute or alphabetically

### Actual Behaviour

The speakers are listed in reverse alphabetical order

### Platform
**Sermon Manager Version:** 2.13.0
**WordPress Version:** 4.9.5
**PHP Version:** 7.1

### Additional Info

![reverse-alphabetical-order](https://user-images.githubusercontent.com/537684/41207145-671c2b08-6cde-11e8-99f7-21a896db598c.png)

**Comment by nikola3244** [comment]
Hi, can you please tell us how are you displaying the speakers?

If it's via shortcode, could you please send us the full shortcode here?

**Comment by robertmain** [comment]
Yep, sorry - it's via shortcode.

The shortcode I'm using is - `[sermon_images display="preachers" title_wrapper="h4"]`
