### ISSUE TITLE
CMB2

### ISSUE THREAD

**Issue by igor-gp** [WP-for-Church/Sermon-Manager#22]
It is highly recommended the bundled CMB2 be updated to the most recent version, and there is no reason not to as CMB2 maintains backward compatibility.

https://github.com/webdevstudios/CMB2

**Comment by nikola3244** [comment]
Actually, there is a reason why not to. WPFC maybe modified some parts of CMB2 (which is a bad thing to do), and if we update it, we will risk to introduce more bugs.

My vote is to leave it alone. SM 3.0 will be better.
