### ISSUE TITLE
Multiple feeds

### ISSUE THREAD

**Issue by scottdwest** [WP-for-Church/Sermon-Manager#220]
### Expected Behaviour
https://example.com/?feed=rss2&post_type=wpfc_sermon&wpfc_service_type=morning-service should correctly validate as a feed

### Actual Behaviour
According to http://www.feedvalidator.org, The Atom:link tag url is invalid, apparently it needs to be escaped.

### Platform
**Sermon Manager Version:**  2.13.1
**WordPress Version:**  4.9.6

### Any Additional Info

The feed is accepted by Feedly, but not by Feedburner.

**Comment by nikola3244** [comment]
Hi there!

Could you please send here the actual error message and the `atom:link` line?

**Comment by scottdwest** [comment]
line 12, column 58: XML parsing error: <unknown>:12:58: not well-formed (invalid token)
`12. <atom:link href="http://gochurch.cc/?feed=rss2&post_type=wpfc_sermon&wpfc_service_type=manchester" rel="self" type="application/rss+xml"/>`

**Comment by scottdwest** [comment]
Additionally when trying to validate using FeedBurner using the above url format I get the following error:
`The URL does not appear to reference a valid XML file. We encountered the following problem: Error on line 12: The reference to entity "post_type" must end with the ';' delimiter.`

**Comment by scottdwest** [comment]
Removing all references to atom from "wpfc-podcast-feed.php" allows the feed to validate using https://podba.se/validate/ (as recommend by Apple - https://help.apple.com/itc/podcasts_connect/#/itcac471c970) and also generates the desired results with Feedly and FeedBurner.

**Comment by nikola3244** [comment]
Fixed!

The problem was that `&post_type=wpfc_sermon` was not url-encoded (also `&wpfc_service_type=manchester)`, so parsers thought that `post_type` is an entity (such as `amp` in `&amp;` is)

That's also the reason for the second error. It just says that there's no semicolon at the end of (invalid) entity. i.e. `&post_type;`

Anyway, it has been fixed now
