### ISSUE TITLE
Player button doesn't change to "Pause" while the audio is playing

### ISSUE THREAD

**Issue by robertmain** [WP-for-Church/Sermon-Manager#232]
### Expected Behaviour
When the audio is playing, the "Pause" icon should be displayed to indicate that the audio is playing and can be paused.

The border also appears to be missing from the player. Not sure if related, but I can open a new issue for that if not.

### Actual Behaviour
Currently, the "Play" icon is still displayed.

### Steps To Reproduce

1. Find any sermon
2. Click "Play"

### Platform
**Sermon Manager Version:**  2.14.0
**WordPress Version:**  4.9.5
**PHP Version:** 7.1

### Any Additional Info
![image](https://user-images.githubusercontent.com/537684/45591741-94bc5100-b928-11e8-9caf-fe073985670d.png)
![image](https://user-images.githubusercontent.com/537684/45591742-9c7bf580-b928-11e8-855e-c2579e2941b3.png)

**Comment by nikola3244** [comment]
Hi,

Thanks for the report! :hearts:

Could you please confirm that the bug still exists in latest code from `dev` branch?
I've tried to fix that exact issue in https://github.com/WP-for-Church/Sermon-Manager/commit/0ba5f24a4667d05bfb5c7c80a7ceb87212e4655b, and the fix worked in my tests, but I've maybe missed something.

(Also, just a reminder, don't forget to clear browser cache. :slightly_smiling_face:)

**Comment by robertmain** [comment]
I just uploaded 0ba5f24 and the sermon page redirects to my home page, while the home page (with sermons normally embedded) just has the un-parsed shortcodes displayed.

I just uploaded the code in place of 2.14.0. Is there something else I need to do?

**Comment by robertmain** [comment]
....nevermind - I named the directory wrong. 

Yeah, it's working now. Both of the issues I mentioned are resolved, so I'm gonna go ahead and close this now.
