### ISSUE TITLE
Webnus Sermon

### ISSUE THREAD

**Issue by anewtoncovenant** [WP-for-Church/Sermon-Manager#237]
### Expected Behaviour
To work

### Actual Behaviour
HTTP 500 ERROR

### Steps To Reproduce

1. 
2. 

### Platform
**Sermon Manager Version:**  Version 1.2.1 
**WordPress Version:**  
**PHP Version:**

**Comment by nikola3244** [comment]
Hi there, this is the support channel for Sermon Manager, not Webnus Sermon (they are two completely different plugins, made by completely different companies). The correct place for ticket submission would be here -> https://webnus.ticksy.com/
