### ISSUE TITLE
Different plugin directory name

### ISSUE THREAD

**Issue by igor-gp** [WP-for-Church/Sermon-Manager#25]
Customers seem to have folders called **sermon-manager-for-wordpress** whereas now its **Sermon-Manager**

This is why the plugin is often deactivated upon update, the folder name has changed. 

Leave it as it is or change it to **sermon-manager-for-wordpress**

**Comment by nikola3244** [comment]
I have just tried to install from WP, folder name is **sermon-manager-for-wordpress**.

How do you get **Sermon-Manager**?
