### ISSUE TITLE
Integrate French translation

### ISSUE THREAD

**Issue by kriks57** [WP-for-Church/Sermon-Manager#257]
Hi,

I translated nearly everything in french : https://translate.wordpress.org/projects/wp-plugins/sermon-manager-for-wordpress/stable/fr/default

Could you please integrate the translations ?

**Comment by nikola3244** [comment]
Hi,

Thank you for the translation! :heart: 

The translation will become active automatically as soon as all strings are approved by the French Translation Editor, who is not related to us in any way. You can ask around in the [French Slack](https://wordpressfr.slack.com/) ([sign up here first](https://wpfr.net/slack/)) to speed it up or you can ask to become a Project Translation Editor for Sermon Manager.

**Comment by kriks57** [comment]
it became available in the last version :)
