### ISSUE TITLE
Can’t Change ‘sermon_images’ Size

### ISSUE THREAD

**Issue by mike-matenkosky** [WP-for-Church/Sermon-Manager#265]
### Expected Behaviour
This should display thumbnails, but it is showing the full-size image:
`[sermon_images display="preachers" order="ASC" orderby="id" size="thumbnail"]`

### Actual Behaviour
The image only shows the full-size. I also changed to `display=series` and it does the same thing.

### Steps To Reproduce

1. Create a new page.
2. Insert the shortcode `[sermon_images display="preachers" order="ASC" orderby="id" size="thumbnail"]`
3. Save page.
4. Should display all Preachers (or Series if using that shortcode) in 'Thumbnail' size.

### Platform
**Sermon Manager Version: 2.15.15**  
**WordPress Version: 5.2.4**  
**PHP Version: 7.2.21**

**Comment by jasonmwestbrook** [comment]
Hey Mike, please check with our latest version 2.16.2 we make some changes to our shortcode parameters

**Comment by mike-matenkosky** [comment]
> Hey Mike, please check with our latest version 2.16.2 we make some changes to our shortcode parameters

Sorry Jason, it's still not working for me. Disabled all plugins and switched to TwentyTwenty. Using `[sermon_images display="preachers" order="ASC" orderby="id" size="thumbnail"]` it shows a medium-sized thumbnail now.
