### ISSUE TITLE
Missing Fields in Add new sermon

### ISSUE THREAD

**Issue by philp413** [WP-for-Church/Sermon-Manager#277]
### Expected Behaviour

When I add a new sermon, there should be fields/boxes for mp3, video, notes, etc etc but currently only boxes available are:
First Column
Sermon title,  
Yoast SEO

Second Column is as normal with: 
Publish
Preachers
Series
Topics
Bible books
Sermon Image

### Actual Behaviour

When I add a new sermon, there should be fields/boxes for mp3, video, etc etc but currently only boxes available are:
First Column
Sermon title,  
Yoast SEO

![Screenshot 2020-08-10 at 10 34 48](https://user-images.githubusercontent.com/48053870/89771753-bd3f2c80-daf8-11ea-9759-fea43bb1fa1f.png)

### Steps To Reproduce

1. 
2. 

### Platform
**Sermon Manager Version:**  Version 2.16.0
**WordPress Version:**  WordPress 5.4.2 running Divi theme
**PHP Version:** unknown not current

**Comment by philp413** [comment]
PHP version: 7.3.6

**Comment by tstephen** [comment]
We experienced this too. I removed the plugin, reinstalled 2.5.17 from a backup and it worked as expected. I then upgraded to 2.16 and now this version works too. So whether there was a corrupted install of 2.16 or even potentially a corrupted 2.16 in the WordPress repo I don't know but this is how I resolved it for us.

**Comment by philp413** [comment]
> We experienced this too. I removed the plugin, reinstalled 2.5.17 from a backup and it worked as expected. I then upgraded to 2.16 and now this version works too. So whether there was a corrupted install of 2.16 or even potentially a corrupted 2.16 in the WordPress repo I don't know but this is how I resolved it for us.

Thanks that worked perfectly, All back to working now
