### ISSUE TITLE
PodTrac Support

### ISSUE THREAD

**Issue by reykroona** [WP-for-Church/Sermon-Manager#28]
I'd love to see the addition of PodTrac (http://analytics.podtrac.com) tracking support in the RSS feed for podcasts. It simply adds to the link "http://dts.podtrac.com/redirect.mp3/" to the begging of the enclosure url. PodTrac then tracks downloads for you. 

Maybe having a checkbox in the podcast options page in the setting to turn it on or off with a link to how to set it up.

I was able to hard code it into our site, but including it as an official feature would be nice for us for upgradeability. 

If I have time I'll clone the project and see if I can add it, then request a pull request.

**Comment by reykroona** [comment]
Here's our feed if you want to see a sample: http://madeforfellowship.com/sermons/feed/

**Comment by nikola3244** [comment]
Bugs are our top priority right now, but if you submit a PR we'll gladly merge it into core. :+1:

**Comment by reykroona** [comment]
#29 Submitted a PR

**Comment by nikola3244** [comment]
Merged
