### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by mal-tee** [WP-for-Church/Sermon-Manager#307]
Hello maintainer(s),

I am a security researcher from the Institute of Application Security at TU Braunschweig, Germany. We discovered a (potential) security vulnerability in your project.

We would like to report this vulnerability to you in a responsible and ethical manner.
Therefore, we do not want to disclose any details of the vulnerability publicly until you have had a chance to review and fix it.

Could you please let us know your prefered way of receiving security reports?

You can contact us at [ias-disclosure@tu-braunschweig.de](mailto:ias-disclosure@tu-braunschweig.de) or by replying to this issue.

Thank you for your attention and cooperation.

**Comment by GermanKiwi** [comment]
Hi there, just FYI, the current owners of the Sermon Manager plugin do not use or maintain this Github, and therefore will not have seen this issue.

You can contact them via their website at https://wpforchurch.com/my/contact.php or their plugin page at https://wordpress.org/plugins/sermon-manager-for-wordpress/

**Comment by mal-tee** [comment]
thanks!
