### ISSUE TITLE
Adding menu items when Sermons is a parent causes 404

### ISSUE THREAD

**Issue by igor-gp** [WP-for-Church/Sermon-Manager#31]
Need further testing but it seems when a you try and put a menu item as a child of a Sermons page, it causes 404. Tested on Multiply Theme

**Comment by nikola3244** [comment]
This is expected behavior. WP looks for a sermon with the slug of the child page

If this is an important bug, I think that I can find a solution for this

**Comment by nikola3244** [comment]
Seems like this is also an invalid bug now. Demo works just fine: demo.wpforchurch.com/multiply/
