### ISSUE TITLE
Wrong RFC822 date and time stamps in podcasts RSS feed

### ISSUE THREAD

**Issue by GITNE** [WP-for-Church/Sermon-Manager#37]
The current podcast RSS feed implementation produces *localized* [RFC822 date and time stamps](https://tools.ietf.org/html/rfc822#section-5) in the body of the [`pubDate`]() element of the [`item`](http://www.rssboard.org/rss-2-0#hrelementsOfLtitemgt) element instead of date and time stamps in the `C` or `POSIX` locale (often effectively the `en_US` locale). This violates the [RSS 2.0 and also RFC822 date and time specifications](http://www.rssboard.org/rss-2-0#ltpubdategtSubelementOfLtitemgt), and thus causes consumers of a feed, exported by systems configured to other locales than `C`, `POSIX`, or `en`, to error out or ignore the time stamp.

Note that although the RSS 2.0 specification speaks of RFC822 which has been superseded by [RFC5322](https://tools.ietf.org/html/rfc5322) by now, even [RFC5322](https://tools.ietf.org/html/rfc5322#section-3.3) does not specify *localized* date and time stamps (which makes perfect sense). It is pretty safe to assume that the RSS 2.0 specification by referencing any RFC also implies any latest RFC to apply as long as it is backwards compatible (which is true for RFC5322).

Interestingly, the implementation produces correct date and time stamps in the body of the [`lastBuildDate`](http://www.rssboard.org/rss-2-0#optionalChannelElements) element regardless of the exporting system's (or process') current locale.

**Comment by nikola3244** [comment]
Thanks for the report, but `pubDate` element generation is handled by WordPress itself. If you believe that there is a bug, submit it to official WordPress bug tracker: https://core.trac.wordpress.org/

Related line: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/feed-rss2.php#L92

**Comment by GITNE** [comment]
> Thanks for the report, but `pubDate` element generation is handled by WordPress itself.

This statement is partly incorrect, or only partly correct, depending on how you look at it.

It may be correct (and probably is) for the child `pubDate` element of the `channel` element, however it is not for the child `pubDate` element of the **`item`** element. I did take a closer look at Sermon-Manager's RSS feed code. The later (`item` case) is definitely currently handled by the Sermon-Manager directly. Hence, please reopen this issue because it only pertains to the Sermon-Manager.

**Comment by nikola3244** [comment]
Thanks for adding additional comments.

The [line of code](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/feed-rss2.php#L92) that I have sent is from official WordPress RSS2 code. And it is used for creating `pubDate` element as a child of `item` element, as you can see the opening `item` tag [just couple lines above it](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/feed-rss2.php#L86).

It is true, we have copied that line into our own RSS2 template, as you can see [here](https://github.com/WP-for-Church/Sermon-Manager/blob/dev/views/wpfc-podcast-feed.php#L48). It is completely identical to official WordPress code.

So, if there is a bug in Sermon Manager code, that means that it is present in the WordPress itself.

Unfortunately, we do not have time or resources to fix core WordPress issues, so please, if you believe that there is an issue, create it in [the official WordPress bug tracker](https://core.trac.wordpress.org/). As soon as they fix it, we will update the code in Sermon Manager.

**Or**, if you have time and knowledge, make a pull request and we will gladly accept it. (And again, you could also make a pull request or open an issue on WordPress bug tracker as well)

**Comment by GITNE** [comment]
Perhaps I should have added which RSS feed I am referring to. The issue refers to the podcast RSS feed of the Sermon Manager, not the sermons feed itself.

Currently, I do not have much time to dig deeper into the Sermon Manager code either but I may post a PR to fix this issue some time in the future.

**Comment by nikola3244** [comment]
Yeah, I've been talking about podcast RSS feed whole time. The links in my previous comments lead all to `wpfc-podcast-feed.php` file. So, it's for podcasts

**Comment by GITNE** [comment]
At first glance, the code may look identical to WordPress RSS code, however it does not behave like WordPress code. There is some sort of function redirection or aliasing going on. The function effectively responsible for generating the `pubDate` element's body time stamp string in the `item` element of Sermon Manager is [`wpfc_sermon_date()`](https://github.com/WP-for-Church/Sermon-Manager/blob/master/includes/podcast-functions.php#L175). I am not a PHP expert, so I am unable identify the root cause of the issue or what to actually fix yet. But, it is definitely not working as intended. To me, https://github.com/WP-for-Church/Sermon-Manager/blob/master/includes/podcast-functions.php#L24 looks like where this sort of function alias is going off the rails (so to speak).

Test, test, and once again test. Do not assume anything unless you have looked through the full calling stack.
