### ISSUE TITLE
Make date field optional

### ISSUE THREAD

**Issue by adi8i** [WP-for-Church/Sermon-Manager#39]
If a date is not picked it breaks the loop / posts return null. I think will be better if we make it optional.

**Comment by nikola3244** [comment]
@adi8i that field won't even exist in v3, but could you give me the exact error so I could patch it in v2? Thanks

**Comment by nikola3244** [comment]
FYI, date field has been removed from v2. Sermon Manager 2.4.7+ will rely just on default WP date. Our theme views should be updated as well

**Comment by adi8i** [comment]
Ok, so we'll be using `post.date` ?

**Comment by nikola3244** [comment]
Yup, that's the correct way from now on :)

But you should maybe put some checks for SM instances that are not updated
though
