### ISSUE TITLE
Sortlist problem when nothing selected

### ISSUE THREAD

**Issue by paulkosciecha** [WP-for-Church/Sermon-Manager#43]
When using the sortlists to filter the content this works fine when you select a series/preacher etc. However, when you then go back to having no item selected you do not return to the sermon list, but to the blog page.

**Comment by paulkosciecha** [comment]
Hi, I've managed to bypass this problem on my install. The solution I've used is to set 'Common Base Slug' to on in the sermon manager settings. I've then modified the template-tags.php file so that the action is not just calling the home_url(), but home_url().'/sermons/' . This way, when the value is empty it resolves to the sermons page. The issue is to do with the submit action url which directs to the homepage when the selection is empty.

**Comment by nikola3244** [comment]
Hey @paulkosciecha, could you make a pull request so we could make this fix official? :+1:

**Comment by paulkosciecha** [comment]
Hi nikola3244. The solution that I've put in place isn't a full fix, just a work around that means it works on my site. If 'Common Base Slug' is not set to on then it doesn't work.

**Comment by nikola3244** [comment]
Oh, I see. Okay, I'll take a look and make a proper fix. Thanks for the report :slightly_smiling_face:

**Comment by paulkosciecha** [comment]
Hi, just checked your fix. It's still not working. Try clicking on a series title to go to a series page - url is something like - http://www.siteurl.com/series/series-title . The sortlists are showing. When you then try to use the sortlist you go to a 404 page.

**Comment by nikola3244** [comment]
Hey @paulkosciecha, I encountered the same issue after you mentioned it. Try saving plugin settings again (open Sermon Manager settings page and without modifying any data - click on "Save Changes"). That seemed to resolve the issue on my end

**Comment by paulkosciecha** [comment]
sorry, that doesn't appear to work for me. Because it points to a 'series' page rather than the 'sermons' page it fails.

**Comment by nikola3244** [comment]
Hey @paulkosciecha, can you try with the latest fix?

Thanks

**Comment by paulkosciecha** [comment]
Yes, great. That does the trick.

**Comment by nikola3244** [comment]
Perfect. Glad to hear that it's resolved :slightly_smiling_face:
