### ISSUE TITLE
Filter/Page bug

### ISSUE THREAD

**Issue by igor-gp** [WP-for-Church/Sermon-Manager#70]
There is a bug with navigation and filter, to reproduce - go to sermons page 2 and then use filter, it causes a 404 since the URL takes into account page 2 and hence errors out. 

https://www.useloom.com/share/a2c08b7451834d7289925a8d0f3b12c1

The URL in that example ended up being `https://northcoastchurch.org.au/sermons/page/2/?wpfc_sermon_series=advance-appeal` instead of `https://northcoastchurch.org.au/sermons/?wpfc_sermon_series=advance-appeal`

**Comment by nikola3244** [comment]
Dupliate of #43
