### ISSUE TITLE
Remove or change Creator in podcast feed

### ISSUE THREAD

**Issue by tythewebguy** [WP-for-Church/Sermon-Manager#75]
My WordPress username is appearing in the CDATA for <dc:creator>. Being a behind-the-scenes admin, my name shouldn't be in the RSS feed. It would be nice to toggle that off in settings, or change it to something else.

**Comment by nikola3244** [comment]
The call for username is there, but that file is never called. There's `die()` function at the top, so nothing will be executed and your username won't be exposed.

The file remained there after some refactoring and was forgotten. We will get back to it shortly. :)
