### ISSUE TITLE
"&copy;" does not validate in Podcast settings

### ISSUE THREAD

**Issue by tythewebguy** [WP-for-Church/Sermon-Manager#76]
**Settings** > **Podcast** > **Copyright** suggests entering **`&copy;`** for the copyright symbol, but it inserts the `&copy;` HTML entity into the feed, which doesn't validate. If the settings are saved a _second_ time, the © symbol is saved instead of the HTML entity, and everything validates okay.

**Comment by nikola3244** [comment]
Possible fix in 2aad6a3d25427d810a4f3026480dcc33c676538b
