### ISSUE TITLE
Archive Page Slug changes require saving twice

### ISSUE THREAD

**Issue by tythewebguy** [WP-for-Church/Sermon-Manager#78]
I've been able to replicate this several times in my local dev instance and my production sites.

When I save **Settings** > **General** > **Archive Page Slug** and click **Save Changes**, the change _appears_ to be saved, but when I visit the new slug I get a 404...but the old slug still works. When I click the **Save Changes** button a second time--without making any changes--the slug begins to work correctly.

This seems similar to #76.

**Comment by nikola3244** [comment]
Similar to #76, but not the same. For some reasons, rewrite rules are not flushed on first save. Weird, but we will fix it.

Thank you so much for helping us make Sermon Manager a better plugin!
