### ISSUE TITLE
Podcast Top/Sub Category enhancement

### ISSUE THREAD

**Issue by tythewebguy** [WP-for-Church/Sermon-Manager#81]
Other podcasting plugins use SELECT drop-downs for choosing the iTunes categories to eliminate human error when choosing categories. This would be a great enhancement.

![image](https://user-images.githubusercontent.com/1933030/30191113-9dabd606-93f3-11e7-83fa-7dbbf60fe745.png)

Options in Category:

![image](https://user-images.githubusercontent.com/1933030/30191122-a661a28a-93f3-11e7-83f3-b47899c1352b.png)

Options in Sub-Category:

![image](https://user-images.githubusercontent.com/1933030/30191130-b16532fa-93f3-11e7-923c-861d99918255.png)

From a usability perspective, I'm not sure why two selects are needed when the second one lists the top categories AND the sub-categories (although the top category is not enabled in the list...but it easily could be, so a user can choose just the top category, or the top+sub category).

**Comment by nikola3244** [comment]
Fixed in 2.9, https://github.com/WP-for-Church/Sermon-Manager/commit/35f328892d7c86be2c676371b3721a7ff3f42bdd#diff-482a44a5255193f0431efa49f691e3caR116
