### ISSUE TITLE
Service Type cannot be saved as None

### ISSUE THREAD

**Issue by tythewebguy** [WP-for-Church/Sermon-Manager#84]
If a sermon has its **Service Type** set, then later changed back to **None**, that change will not be saved.

**Comment by nikola3244** [comment]
Hey @tythewebguy,

We just got to fixing this bug, but strangely, it works as expected on our end. (Changing **Service Type** to **None** works without any issue)

So, let's add some more details to this issue. What are your WordPress and PHP versions?

**Comment by tythewebguy** [comment]
Strange...it's working correctly now. I guess this can be closed.

**Comment by nikola3244** [comment]
Very strange, but we will fix it if it shows up again. Thank you for reporting it!
