### ISSUE TITLE
Issue with template-tags file in 2.5.2

### ISSUE THREAD

**Issue by paulkosciecha** [WP-for-Church/Sermon-Manager#89]
Hi, I'm getting an error in the sortlist area of the page with 2.5.2. There is an illegal offset at line 204 of the template-tags.php file. Here's the code I've used and it appears to work. Please could you check it's still doing what it's meant to be doing.
Old code:

unset( $hidden[ $filter ] );

new code:

unset( $hidden[ $filter['taxonomy'] ] );

**Comment by paulkosciecha** [comment]
This is not yet fixed. When you drill into one of the filters you still get the errors. The code should be:

if ( ! empty( $hidden ) && ! empty( $hidden[ $filter['taxonomy'] ] ) ) {
				unset( $hidden[ $filter['taxonomy'] ] );

$filter here is an array and therefore an invalid offset on the $hidden array.

**Comment by nikola3244** [comment]
Thanks for the report and fix, but [we will revert](https://github.com/WP-for-Church/Sermon-Manager/issues/95) filtering to "hyperlink"/quick link functionality like it was before. So, the fix will be invalid. Thank you for understanding :slightly_smiling_face:
