### ISSUE TITLE
Podcast Feed issues

### ISSUE THREAD

**Issue by igor-gp** [WP-for-Church/Sermon-Manager#9]
Sitemap invalid errors.

Another user reported - http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fvictorybaptistpocono.com%2Ffeed%2Fpodcast

**Comment by igor-gp** [comment]
Customer feedback:

`I was able to locate the source of the error that prevents customizing shortcode output.
On line 261 of "/includes/shortcodes.php"
You have <?php wpfc_sermon_excerpt(); ?>
It should be <?php do_action( 'sermon_excerpt' ); ?>


Also, I would really like to see the following improvements to the podcast feature

Removing the duplicate enclosures
In "/includes/podcast-functions.php"
Add this function

function wpfc_podcast_delete_enclosure() {
return '';
}
The add this to the wpfc_modify_sermon_date function (Approx Line 127 of "/includes/podcast-functions.php")
add_filter( 'rss_enclosure', 'wpfc_podcast_delete_enclosure' );



Rewriting https URLs to http as only http is considered valid
On line 48 of "/includes/podcast-functions.php"
Replace $audio = get_post_meta($post->ID, 'sermon_audio', 'true');
With $audio = str_ireplace('https://', 'http://', get_post_meta($post->ID, 'sermon_audio', 'true'));
On line 67 of "/includes/podcast-functions.php"
Replace $post_image = ( $post_image ) ? $post_image['0'] : null;
With $post_image = str_ireplace('https://', 'http://', ( $post_image ) ? $post_image['0'] : null);`

**Comment by igor-gp** [comment]
https://wordpress.org/support/topic/2-0-has-breaking-changes/#post-8682476

**Comment by igor-gp** [comment]
https://wordpress.org/support/topic/various-bug-fixes/

**Comment by nikola3244** [comment]
There are actually two issues here, moving sitemap issue to separate one.
